### ISSUE TITLE
Show list of goals on home page

### ISSUE THREAD

**Issue by chill117** [Learn-by-doing/bitstarter#3]

**Comment by bokova** [comment]
What data do we want to surface show on the homepage?

**Comment by chill117** [comment]
@bokova I think name of the goal, visual progress bar (with total amount of goal), and a link to donate to the goal.

Reference links:
- https://expressjs.com/
- http://handlebarsjs.com/

**Comment by bokova** [comment]
Hey @victorbrender did you already decide what structure the data that's meant to be surfaced on the HP will have?

**Comment by victorbrender** [comment]
Hey @bokova ,
Unfortunately I didn't have time to write some code and get the data structure working but I think something like this should work for displaying the array of projects:

var projects = [{
  name: string,
  targetAmount: number,
  amountCollected: number,
  donateURL: string
},
{
  name: string,
  targetAmount: number,
  amountCollected: number,
  donateURL: string
},
{
  name: string,
  targetAmount: number,
  amountCollected: number,
  donateURL: string
},
...
]

What do you think?

**Comment by bokova** [comment]
Right now I'm a bit more verbose having:

```
var content = { projects: [ 
        {
            name: string,
            description: string,
            goal_total: number,
            goal_collected: number,
            goal_percentage: number,
            donate_link: string
        }
        , {
            ...
        }, {
            ...
        }]};
```

I'll try to be there on Monday (might be a bit late) so we can modifyif needed and most importantly you can show me how to git this properly :)

**Comment by victorbrender** [comment]
@bokova 
I am not in Prague for the next 2 meetups so I think you'll have to work with @chill117 on this issue.
One observation I have is that in JS the camelcase notation is prefered for variable names(see -> http://javascript.crockford.com/code.html ). In ruby land from I come from we also use the snake notation (eg: 'test_name') but I learnt that it is easier to adopt each language's set of rules to make my interaction with other programmers easier.
