### ISSUE TITLE
List all existing projects.

### ISSUE THREAD

**Issue by victorbrender** [Learn-by-doing/bitstarter#43]
Extracted from https://github.com/Learn-by-doing/bitstarter/issues/7

**Comment by victorbrender** [comment]
I'll take this one.

**Comment by victorbrender** [comment]
Implemented in https://github.com/Learn-by-doing/bitstarter/pull/56

**Comment by victorbrender** [comment]
I would like to add some tests that check that the projects are correctly displayed in the view but my instinct is to create a new issue for this. What do you guys think?

**Comment by karliatto** [comment]
I think it's a good idea to create an issue for this propose as well as  for testing other parts of the code
