### ISSUE TITLE
Implement "Edit project" functionality 

### ISSUE THREAD

**Issue by victorbrender** [Learn-by-doing/bitstarter#45]
Extracted from https://github.com/Learn-by-doing/bitstarter/issues/7

**Comment by bokova** [comment]
would you mind if I claimed this?

which approach would you like to take @chill117?
edit the properties on a standalone page (hence loading the data of the project with the load of the page) 
OR
edit the properties in the page with the project listing, so all is done on the background as AJAX?

**Comment by ipovalyaev** [comment]
I've taking this :)

**Comment by ipovalyaev** [comment]
I've came to a set of questions how to do some features to make multiply token. I'll have to add and remove edit fields for tokens dynamically to the form and I missing the knowledge - which approaches/libraries/techniques should be used for this. Also, seems to me it's not a very good idea to write to database every time once address added or removed - it's better to do it in once step. But for this I'll have to store all the changes somewhere. And I have no idea where :)

**Comment by victorbrender** [comment]
I think this is not a concern for this particular issue. Here, you only have to add the functionality for editing a project that has a single token. We will only have to deal with multiple token edit functionality once we introduce the ability to create projects with multiple token.
