### ISSUE TITLE
Home page changes

### ISSUE THREAD

**Issue by chill117** [Learn-by-doing/bitstarter#61]
@bokova said:

> * semantic HTML
> * responsive design
> * no bootstrap
> * keep theme
> * no pagination, view everything
> * newest project on top

Plus:
* Login, logout, etc links should be in top-right corner of every page
* Show amount received so far (and percentage)

**Comment by victorbrender** [comment]
I think these should all be separate issues. If you agree, I can create the separate issues and then ping you to close this one. @chill117

**Comment by bokova** [comment]
Could look like this:

![image](https://cloud.githubusercontent.com/assets/12925487/20679208/3c203cc0-b59a-11e6-980a-9d7e83496230.png)

**Comment by bokova** [comment]
* semantic HTML
* responsive design
* no bootstrap
* keep theme
* no pagination, view everything
* newest project on top

**Comment by olios** [comment]
@bokova - May I contribute on your homepage design proposal?

**Comment by chill117** [comment]
I think most of this has been done by #97. Let's create new (smaller) issues for any more things we want to change to the home page.
