### ISSUE TITLE
Admin area: List goals (delete, add, edit)

### ISSUE THREAD

**Issue by chill117** [Learn-by-doing/bitstarter#7]

**Comment by lenkakadlec** [comment]
Hello, I've set up the bcrypt-nodejs, so I can join. Can you provide more info on this task?

**Comment by victorbrender** [comment]
Well, this is a "catch all" task and maybe it should have been broken down into smaller pieces. I'll try to do that tomorrow and close some of them for which I have already written some code. At the moment this is what I have until now: https://github.com/Learn-by-doing/bitstarter/compare/master...victorbrender:admin-section-wip?expand=1

**Comment by chill117** [comment]
@crystalarc Could you create a pull request with the changes you had to make to get bcrypt-nodejs to work with Windows?

Yes, @victorbrender is right. This task should be split into smaller tasks.

**Comment by victorbrender** [comment]
@chill117  I have broken down this issue into more approachable ones. Please close this one.
